openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Elios Fund API'
  description: The Elios Fund API provides a robust interface for partners to integrate and access the most powerful financing options in Solar today.
  contact:
    name: Elios Fund Engineering
    url: https://portal.support.eliosfund.com
    email: engineering@eliosfund.com

externalDocs:
  url: https://partners.eliosfund.com
  description: Manage your Elios Fund API keys and OAuth 2.0 clients.

servers:
  - url: https://api.eliosfund.com
    description: All requests should be directed to the production environment.
  - url: https://api.staging.eliosfund.com
    description: For access to the staging environment, please contact Elios Fund support.

paths:
  /projects:
    get:
      summary: Get all projects
      description: Returns all available projects.
      security:
        - ApiKey:
          - view:projects
        - OAuth:
          - view:projects
      responses:
        200:
          description: All projects assigned to your account.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ProjectCollection'
        401:
          description: There was no API key provided with the request or the API key was invalid.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'     
        403:
          description: The API key provided does not contain the proper scopes for the current request.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'            
        500:
          description: There was an unexpected server error.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects/{projectId}:
    parameters:
      - name: projectId
        description: The unique identifier of the project. This can be the Project ID or Proposal ID.
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ProjectId'
    get:
      summary: Get a project
      description: Returns all available information about a single project.
      security:
        - ApiKey:
          - view:projects
        - OAuth:
          - view:projects
      responses:
        200:
          description: The project corresponding to the provided `projectId`.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Project'
        401:
          description: There was no API key provided with the request or the API key was invalid.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'     
        403:
          description: The API key provided does not contain the proper scopes for the current request.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'            
        404:
          description: The requested resource was not found.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: There was an unexpected server error.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ActionItemIri:
      description: The unique JSON-LD IRI reference to the action item.
      type: string
      format: uri
      example: '/action-items/1'
    AddressIri:
      description: The unique JSON-LD IRI reference to the address.
      type: string
      format: uri
      example: '/addresses/1'
    AttachmentIri:
      description: The unique JSON-LD IRI reference to the attachment.
      type: string
      format: uri
      example: '/attachments/1'
    CustomerIri:
      description: The unique JSON-LD IRI reference to the customer.
      type: string
      format: uri
      example: '/customers/1'
    CommentIri:
      description: The unique JSON-LD IRI reference to the comment.
      type: string
      format: uri
      example: '/comments/1'
    DealerIri:
      description: The unique JSON-LD IRI reference to the dealer.
      type: string
      format: uri
      example: '/dealers/1'
    DistributorIri:
      description: The unique JSON-LD IRI reference to the distributor.
      type: string
      format: uri
      example: '/distributors/1'
    InstallerIri:
      description: The unique JSON-LD IRI reference to the instsaller.
      type: string
      format: uri
      example: '/installers/1'
    ProjectIri:
      description: The unique JSON-LD IRI reference to the project.
      type: string
      format: uri
      example: '/projects/1'  
    UserIri:
      description: The unique JSON-LD IRI reference to the user.
      type: string
      format: uri
      example: '/users/1'
    ApplicationStatus:
      description: The customer qualification application status.
      type: string
      enum:
        - open
        - submitted
        - onhold
        - approved
        - declined
        - none
        - cancelled
    ProjectId:
      description: The unique identifier of a project.
      type: integer
    ProjectProposalId:
      description: A second unique identifier of a project.
      type: string
    ProjectPhase:
      description: The current project phase.
      type: string
      enum:
        - commissioning
        - customer_survey
        - design
        - final_payment
        - first_payment
        - initial_review
        - inspection
        - install
        - install_qa
        - interconnection
        - ntp_review
        - ntp_submission
        - permitting
        - procurement
        - pto
        - rebates
        - sale
        - site_survey
    ProjectStatus:
      description: The current project status.
      type: string
      enum:
        - new
        - cancelled
        - in_progress
        - on_hold
        - complete
    Project:
      type: object
      required:
        - status
        - phase
        - address
      properties:
        "@id":
          $ref: '#/components/schemas/ProjectIri'
        "@type":
          type: string
          description: The JSON-LD resource type.
          example: Project
        id:
          $ref: '#/components/schemas/ProjectId'
        proposalId:
          $ref: '#/components/schemas/ProjectProposalId'  
        status:
          $ref: '#/components/schemas/ProjectStatus'  
        phase:
          $ref: '#/components/schemas/ProjectPhase'
        applicationStatus:
          $ref: '#/components/schemas/ApplicationStatus'
        packagePrice:
          description: The total contract price.
          type: number
        panelCount:
          description: The number of solar panels involved in the system.
          type: number
        panelWatts:
          description: The wattage of an individual panel.
          type: number
        systemSize:
          description: The size of the system in kW.
          type: number
        systemProduction:
          description: The yearly system energy production in kWh.
          type: number
        proposalLink:
          description: The link to the project proposal.
          type: string
        amountFinanced:
          description: The amount financed by the customer.
          type: number
        downPayment:
          description: The down payment required.
          type: number
        introductoryTerm:
          type: number
        introductoryPayment:
          type: number
        federalRebate:
          type: number
        stateRebase:
          type: number
        utilityRebate:
          type: number
        loanProductName:
          type: string
        loanDealerFee:
          type: number
        loanApr:
          type: number
        loanTerm:
          type: number
        contractRate:
          type: number
        basePpw:
          type: number
        proposalDate:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        address:
          $ref: '#/components/schemas/AddressIri'
        customer:
          $ref: '#/components/schemas/CustomerIri'
        dealer:
          $ref: '#/components/schemas/DealerIri'
        distributor:
          $ref: '#/components/schemas/DistributorIri'
        installer:
          $ref: '#/components/schemas/InstallerIri'
        user:
          $ref: '#/components/schemas/UserIri'
        actionItems:
          type: array
          items:
            $ref: '#/components/schemas/ActionItemIri'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/AttachmentIri'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentIri'
    ProjectCollection:
      allOf:
        - $ref: '#/components/schemas/HydraCollectionMetadata'
        - type: object
          properties:
            totalItems:
              type: integer
              description: The total number of projects.
              example: 5
            member:
              type: array
              description: A list of projects.
              items:
                $ref: '#/components/schemas/Project'
    HydraCollectionMetadata:
      type: object
      properties:
        "@context":
          type: string
          description: The JSON-LD context.
          example: "/contexts/Project"
        "@id":
          type: string
          description: The JSON-LD unique IRI for the collection.
          example: "/projects"
        "@type":
          type: string
          description: The JSON-LD type of the collection.
          example: "Collection"
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: http
      scheme: Bearer
      bearerFormat: JWT
    OAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://partners.eliosfund.com/oauth/authorize
          tokenUrl: https://partners.eliosfund.com/oauth/token
          refreshUrl: https://partners.eliosfund.com/oauth/refresh
          scopes:
            view:action:items: Can view action items
            view:addresses: Can view addresses
            view:attachments: Can view attachments
            view:comments: Can view comments
            view:dealers: Can view dealers
            view:distributors: Can view distributors
            view:installers: Can view installers
            view:partners: Can view partners
            view:projects: Can view projects
            view:users: Can view users
        clientCredentials:
          tokenUrl: https://partners.eliosfund.com/oauth/token
          scopes:
            view:action:items: Can view action items
            view:addresses: Can view addresses
            view:attachments: Can view attachments
            view:comments: Can view comments
            view:dealers: Can view dealers
            view:distributors: Can view distributors
            view:installers: Can view installers
            view:partners: Can view partners
            view:projects: Can view projects
            view:users: Can view users
security:
  - ApiKey: []
  - OAuth: []